### ISSUE TITLE
Errors on IPhone 

### ISSUE THREAD

**Issue by JS96435** [andrew867/timeclock#1]
When you restrict by IP, the IPhone 5 (Not on IPhone 4S)displays the Timeclock page and you get to view every staff member in the office along with Warnings mysql_query() access denied over an 4G LTE network. On all of the pages.
Warning at the top of the page **Your database is out of date**". It is not present when the IP restriction enables the IP via a Wifi network.

On the Android the restriction seems to work fine with "You are not authorized to view this page message". No user data is displayed.

**Comment by andrew867** [comment]
I'll close this for now until you can provide some logs, enable ip_logging and try punching in/out from the iPhone 5 and send a screenshot or copy of the punch report including IPs. The function that parses the IP might be having an issue with the iPhone on your mobile network (most mobile providers use internal address space for phones and use transparent proxying/NAT).
