### ISSUE TITLE
A valid From Date is required.

### ISSUE THREAD

**Issue by southwesttech** [andrew867/timeclock#11]
I downloaded and installed the latest.  Ran the create_tables.sql.  When I try to run a report... I get the following: A valid From Date is required.

I also noticed that the user summary page is blank.

Am I missing something?

**Comment by jconit** [comment]
THANK YOU!!! lqstota..

**Comment by celebiwolf** [comment]
I did the following recommended fix and I am still getting the "A valid To Date is required." error on all reports.

} elseif (!preg_match('/' . "^([0-9]?[0-9])+[-|\/|.]+([0-9]?[0-9])+[-|\/|.]+(([0-9]{2})|([0-9]{4}))$" . '/i', $to_date, $date_regs)) {

**Comment by TravisCook** [comment]
Yes, thank you lqstota!

**Comment by andrew867** [comment]
@TravisCook Could you provide a diff of the fixes you made and I'll merge them into the project.

**Comment by benscanfiles** [comment]
@andrew867 In my pull request, I already fixed this issue. You can close this report :-)

**Comment by andrew867** [comment]
@benscanfiles Thanks!
