### ISSUE TITLE
No migration documentation

### ISSUE THREAD

**Issue by climbthemt** [andrew867/timeclock#13]
Moving from Timeclock-1.04 to the Andrew867/timeclock, there is no explaination of migration path. Whatever migration changes to be done, if any, should be outlined.

**Comment by andrew867** [comment]
You are correct, it should be outlined. If you already have an old 1.04 installed then all you need to do is backup your current install directory, delete all files in the directory, copy Andrew867/timeclock files to the folder, and then finally change the new `config.inc.php` options to match your old file (be sure to set the timezone options correctly and read the comments).

**Comment by andrew867** [comment]
Fixed with commit ea19e67c2f08b738265db59ae6ea71984ba27b61.
