### ISSUE TITLE
"Computes overtime hours."

### ISSUE THREAD

**Issue by boelle** [andrew867/timeclock#30]
how is this done? i cant find anywhere to tell workhours 

and it must need to know workhours etc before it can figure overtime

**Comment by Lucidiot** [comment]
Hello there ! I have no idea if you're still interested by this project, but I found after a few minutes of searching a `$overtime_week_limit` global variable in `punchclock/config.inc.php` (see [here](https://github.com/andrew867/timeclock/blob/708f1822ad82b974fffa223e91eedb4234c259dc/punchclock/config.inc.php#L72)) and a `compute_overtime_hours` function in `punchclock/lib.common.php` ([here](https://github.com/andrew867/timeclock/blob/708f1822ad82b974fffa223e91eedb4234c259dc/punchclock/lib.common.php#L146)).
Maximum work hours are set application-wide and cannot currently be employee-specific, nor can they be set by a specific schedule.
