### ISSUE TITLE
CSV audit reports missing data

### ISSUE THREAD

**Issue by veasnak** [andrew867/timeclock#7]
I cant seem to figure it out, but when the "audit" is ran, and the csv option is selected, the name of the user modified is displayed, but it is not in the csv file. I have tried to add the code to get_csv.php but cant seem to get it right.

**Comment by andrew867** [comment]
I'm not seeing this issue when using the audit log, the CSV I have looks like:

![image](https://cloud.githubusercontent.com/assets/3827955/12040916/6fb184a0-ae47-11e5-9e38-372e20ea8fed.png)

Feel free to open this issue again if you are still having trouble.
